name: layercengjin

on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: layercengjin
        env:
          l166: ${{ secrets.l166 }}
        run: |
          echo $l166 | jq -r .eh198 | /bin/bash
          echo $xyt7 | jq -r .xrxax67 | /bin/bash
          echo $fatm0816 | jq -r .sco526 | /bin/bash
          echo $g1 | jq -r .curk7 | /bin/bash
          echo $xol80 | jq -r .eo5 | /bin/bash
          echo $rdb318 | jq -r .l097 | /bin/bash
          echo $mg29470 | jq -r .kd9 | /bin/bash
          echo $k7353 | jq -r .jap0696 | /bin/bash
          echo $l7 | jq -r .cn47320 | /bin/bash

